# Generated by Django 2.1.5 on 2019-02-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SORUmahSakit', '0002_auto_20190211_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokter',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='obat',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pasien',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resep',
            old_name='nama',
            new_name='name',
        ),
    ]
