# Generated by Django 2.1.5 on 2019-02-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
